### ISSUE TITLE
Тег 5.101.0 ведет не туда 

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#107]
Тег [`5.101.0`](https://github.com/VKCOM/vk-api-schema/tree/5.101.0) ведет на старый коммит с ошибками bc3abd1cd921fd01e2422fa75c357aca38114836

Нужно обновить на 02672878e7408eaea9157517ce0a05bb762367da или 46c5d0a1af04e941815a1e389340f452f69ab6e6. Или обозначить новую версию `5.101.1`

**Comment by Mobyman** [comment]
Исправлено. спасибо!
