### ISSUE TITLE
Размеры превью документов не имеют поля `src`

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#118]
Пример размера превью документа:

```json
{
  "src": "https://sun9-21.userapi.com/c848220/u350160908/d10/-3/m_c8213b2d6d.jpg",
  "width": 130,
  "height": 100,
  "type": "m"
}
``` 

https://github.com/VKCOM/vk-api-schema/blob/02672878e7408eaea9157517ce0a05bb762367da/objects.json#L3409-L3419

https://github.com/VKCOM/vk-api-schema/blob/02672878e7408eaea9157517ce0a05bb762367da/objects.json#L8944-L8965

### Фактический результат

photos_photo_sizes имеет `url`, но не `src`

### Ожидаемый результат

Отдельный объект для размеров превью документа или изменения на уровне API

**Comment by fedorov-xyz** [comment]
Исправили.
