### ISSUE TITLE
Живая обложка у полного объекта сообщества 

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#127]
[groups.getById](https://vk.com/dev/groups.getById) `fields=live_covers`

```json
"live_covers": {
  "is_enabled": true,
  "is_scalable": true,
  "story_ids": ["-131346257_456239025", "-131346257_1397657"]
},
```

### Фактический результат

`groups_group_full` не имеет `live_covers`

### Ожидаемый результат

- [ ] у `groups_group_full` поле `live_covers`
- [ ] объект `groups_group_live_covers`

**Comment by fedorov-xyz** [comment]
Спасибо, исправили.
