### ISSUE TITLE
Добавить метод wall.getComment

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#136]
[wall.getComment](https://vk.com/dev/wall.getComment) появился в 5.92

- [ ] `wall.getComment` в methods.json
- [ ] `wall_getComment_response` в responses.json

### Известные проблемы:

- **likes.can_publish** имеет тип `boolean` вместо `base_bool_int`. Аналогичная проблема у wall.getComments ([bug124318](https://vk.com/bug124318))

**Comment by SevereCloud** [comment]
Актуально

**Comment by fedorov-xyz** [comment]
Спасибо, добавили.
