### ISSUE TITLE
Add groups_group_full `wall`

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#153]
[groups.getById](https://vk.com/dev/groups.getById) `fields=wall`

```json
"wall": 2,
```

---

В `groups_group_full` необходимо добавить следующее поле

```json
"wall": {
    "type": "integer",
    "description": "Wall settings"
}
```

**Comment by fedorov-xyz** [comment]
Спасибо, теперь поле доступно в схеме.
