### ISSUE TITLE
Add groups_group_full `is_adult`

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#155]
[groups.getById](https://vk.com/dev/groups.getById) `fields=is_adult`

```json
"is_adult": 0,
```

---

В `groups_group_full` необходимо добавить следующее поле

```json
"is_adult": {
    "description": "Information whether community is adult",
    "$ref": "#/definitions/base_bool_int"
},
```

**Comment by fedorov-xyz** [comment]
Спасибо, теперь поле доступно в схеме.
