### ISSUE TITLE
Add groups_group_full `has_market_app`

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#156]
[groups.getById](https://vk.com/dev/groups.getById) `fields=has_market_app`

```json
"has_market_app": false,
```

---

В `groups_group_full` необходимо добавить следующее поле

```json
"has_market_app": {
    "type": "boolean",
    "description": "Information whether community has market app"
},
```

**Comment by fedorov-xyz** [comment]
Спасибо, теперь поле доступно в схеме.
