### ISSUE TITLE
Fix groups_group category.id minimum 0

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#157]
https://vk.com/dev/groups.getCatalogInfo

```json
{
  "id": 0,
  "name": "Рекомендации"
}
```

https://github.com/VKCOM/vk-api-schema/blob/adb15c42976ce612c5a6e6a94520feb8ded32973/objects.json#L4778-L4785

https://github.com/VKCOM/vk-api-schema/blob/adb15c42976ce612c5a6e6a94520feb8ded32973/objects.json#L4803-L4810

---

Требуется исправить поле `minimum`

```diff
-          "minimum": 1
+          "minimum": 0
```

**Comment by fedorov-xyz** [comment]
Спасибо! Поправили.
