### ISSUE TITLE
Fix docs_doc_types title

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#159]
https://vk.com/dev/docs.getTypes

```json
{
"id": 1,
"name": "Текстовые",
"count": 126
}
```

https://github.com/VKCOM/vk-api-schema/blob/adb15c42976ce612c5a6e6a94520feb8ded32973/objects.json#L3747-L3764

---

Поле `title` необходимо заменить на `name`

```diff
-        "title": {
+        "name": {
```

**Comment by fedorov-xyz** [comment]
Спасибо! Исправили название поля.
