### ISSUE TITLE
Fix docs_doc_preview_video `file_size`

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#160]
https://vk.com/dev/docs.getById

```json
{
"src": "https://vk.com/do...amp;api=1&mp4=1",
"width": 300,
"height": 264,
"file_size": 171607
}
```

https://github.com/VKCOM/vk-api-schema/blob/adb15c42976ce612c5a6e6a94520feb8ded32973/objects.json#L3715-L3722

---

Необходимо заменить `filesize` на `file_size`

```diff
-        "filesize": {
+        "file_size": {
```

**Comment by fedorov-xyz** [comment]
Исправлено.
