### ISSUE TITLE
Add board_topic_comment `likes`

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#163]
https://vk.com/dev/board.getComments with need_likes=1

```json
{
"id": 11377,
"from_id": 19180,
"date": 1260721280,
"text": "Есть одна ошибка. Некоторые методы так и не представлены в документации. :-)",
"likes": {
    "count": 6,
    "user_likes": 0,
    "can_like": 1
},
"can_edit": 0
}
```

https://github.com/VKCOM/vk-api-schema/blob/adb15c42976ce612c5a6e6a94520feb8ded32973/objects.json#L2779-L2810

---

Необходимо для `board_topic_comment` добавить поле  `likes`

```json
"likes": {
    "$ref": "#/definitions/base_likes_info"
},
```

**Comment by fedorov-xyz** [comment]
Спасибо! Добавили поле в схему.
