### ISSUE TITLE
Fix groups_getCatalogInfo_response `enabled` type

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#165]
https://vk.com/dev/groups.getCatalogInfo

> После успешного выполнения возвращает поле enabled (0 — каталог недоступен для пользователя, 1 — каталог доступен), и, если enabled=1...

---

В `groups_getCatalogInfo_extended_response` и `groups_getCatalogInfo_response` для поля `enabled` необходимо сменить тип

```diff
            "enabled": {
-              "type": "integer",
+              "$ref": "objects.json#/definitions/base_bool_int",
              "description": "Information whether catalog is enabled for current user"
            },
```

**Comment by aotd1** [comment]
Fixed in 5.130.57
