### ISSUE TITLE
Добавить users_user_full поле online_info

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#168]
[users.get](https://vk.com/dev/users.get?params[user_ids]=ba&params[fields]=online_info&params[v]=5.116) `fields=online_info`

```json
{
"online_info": {
"visible": true,
"is_online": true,
"app_id": 6481715,
"is_mobile": true
}
```

---

Необходимо для users_user_full добавить поле online_info

online_info имеет следующие поля
- `app_id` integer
- `last_seen` integer
- `status` string
- `visible` base_bool_int
- `is_online` base_bool_int
- `is_mobile` base_bool_int

**Comment by fedorov-xyz** [comment]
Спасибо, исправили.
