### ISSUE TITLE
Несуществующие указатели

### ISSUE THREAD

**Issue by AlexXanderGrib** [VKCOM/vk-api-schema#174]
Здравствуйте, я захотел сгенерировать типизацию для vk api с помощью `json-schema-to-typescript` по вашим json schema файлам, в процессе генерации он выдал мне несколько ошибок, относящихся к файлу `objects.json`. Вот они:  
  
`Token "actionLinks_action" does not exist.`
`Token "stories_clickable_area" does not exist.`
`Token "snippets_amp" does not exist.`
`Token "articles_article" does not exist.`
`Token "audio_ads_config" does not exist.`
`Token "stories_stat_category" does not exist.`

Пожалуйста добавьте необходимое или удалите ссылки

**Comment by fedorov-xyz** [comment]
Привет, актуальна ли проблема?

**Comment by fedorov-xyz** [comment]
Закрываю за отсутствием активности.
