### ISSUE TITLE
Исправить photos_photo_full `reposts`

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#177]
https://vk.com/dev/photos.getById

```json
"reposts": {
    "count": 2699,
    "user_reposted": 0
},
```

Объект [photos_photo_full](https://github.com/VKCOM/vk-api-schema/blob/0310700f404ebbaec056e3f8123a08bc9c2737d9/objects.json#L9326):

https://github.com/VKCOM/vk-api-schema/blob/0310700f404ebbaec056e3f8123a08bc9c2737d9/objects.json#L9385-L9387

---

Так как объект [base_object_count](https://github.com/VKCOM/vk-api-schema/blob/0310700f404ebbaec056e3f8123a08bc9c2737d9/objects.json#L2401-L2410) не имеет поле `user_reposted`, его необходимо заменить на [base_reposts_info](https://github.com/VKCOM/vk-api-schema/blob/0310700f404ebbaec056e3f8123a08bc9c2737d9/objects.json#L2498-L2511)
 
```diff
 "reposts": { 
-   "$ref": "objects.json#/definitions/base_object_count" 
+   "$ref": "objects.json#/definitions/base_reposts_info" 
 }, 
```

**Comment by fedorov-xyz** [comment]
Спасибо! Исправили.
