### ISSUE TITLE
Несоответствие схемы ответа messages.getConversationsById

### ISSUE THREAD

**Issue by InRedikaWB** [VKCOM/vk-api-schema#178]
Используемая версия: 5.116

Согласно метод возвращать должен:
https://github.com/VKCOM/vk-api-schema/blob/0310700f404ebbaec056e3f8123a08bc9c2737d9/objects.json#L6719-L6778

По факту имеем поле, как минимум, поле chat_settings в котором содержится информация про название чата, юзеров и т.д.

**Comment by fedorov-xyz** [comment]
Спасибо за issue. Проблема исправлена.
