### ISSUE TITLE
storage.get излишние респонсы

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#184]
[storage.get](https://vk.com/dev/storage.get)

> Формат ответа storage.get для одного ключа key изменился, теперь возвращается объект того же типа, что и при передаче keys.

https://github.com/VKCOM/vk-api-schema/blob/7cd0ae0930bee24656459053888b298de3dad681/responses.json#L5203-L5233

https://github.com/VKCOM/vk-api-schema/blob/7cd0ae0930bee24656459053888b298de3dad681/methods.json#L16336-L16344

- `storage_get_response` нигде не используется
~~- `storage_get_v5110_response` тоже самое что и `storage_get_with_keys_response`~~

---

Необходимо оставить только один обновленный `storage_get_response`

```json
 "storage_get_response": { 
   "type": "object", 
   "properties": { 
     "response": { 
       "type": "array", 
       "items": { 
         "$ref": "objects.json#/definitions/storage_value" 
       } 
     } 
   } 
 },
```

**Comment by fedorov-xyz** [comment]
Актуально?

**Comment by SevereCloud** [comment]
Актуально только то, что `storage_get_response` нигде не используется. Вместо него используется `storage_get_v5110_response`. 

`storage_get_with_keys_response` уже удален.

**Comment by fedorov-xyz** [comment]
Исправили. `storage_get_v5110_response` переименовали в `storage_get_response`.
