### ISSUE TITLE
`base_error` плохо задокументирован

### ISSUE THREAD

**Issue by Frago9876543210** [VKCOM/vk-api-schema#196]
На https://vk.com/dev совершенно отсутствует документация по работе с ошибками. В json схеме все поля объекта `base_error` необязательны. То же самое наблюдается с `base_request_param`.
Почему столько полей не помечена, как `required` в ответе сервера?

При работе с ошибками возникает недоразумение. Разработчик получил ошибку от вашего сервиса, а ему приходит примерно такой объект:
```rust
#[derive(Deserialize, Debug)]
struct RequestParam {
    key: Option<String>,
    value: Option<String>,
}

#[derive(Deserialize, Debug)]
enum VkResponse<T> {
    #[serde(rename(deserialize = "response"))]
    Response(T),
    #[serde(rename(deserialize = "error"))]
    Error {
        error_code: Option<i32>,
        error_subcode: Option<i32>,
        error_msg: Option<String>,
        error_text: Option<String>,
        request_params: Option<Vec<RequestParam>>,
    },
}
```

На всякий случай продублирую на вашем хипстерском typescript

```ts
export interface BaseError {
    /**
     * Error code
     */
    error_code?: number;
    /**
     * Error subcode
     */
    error_subcode?: number;
    /**
     * Error message
     */
    error_msg?: string;
    /**
     * Localized error message
     */
    error_text?: string;
    [key: string]: any;
    request_params?: BaseRequestParam[];
}
```

А теперь у нормального разработчика возникает много вопросов от вашего API и json схемы. Допустим, что ваш сервис не отправил мне вообще ничего в объекте `BaseError`. Как в таком случае показывать ошибку юзеру или программисту, который пользуется моей библиотекой?

**Comment by ablearthy** [comment]
Теперь это исправили!
[Было](https://github.com/VKCOM/vk-api-schema/blob/0ec2cf132e481e9e64fc114cf3b6c2bc561081af/objects.json#L2592-L2619)
[Стало](https://github.com/VKCOM/vk-api-schema/blob/master/objects.json#L2554-L2582)

Теперь можно по коду ошибки выводить его `description` (см. `errors.json`)
