### ISSUE TITLE
Параметры `name`, `description`, `category_id` у метода `market.edit` необязательны

### ISSUE THREAD

**Issue by dadyarri** [VKCOM/vk-api-schema#205]
И в песочнице и при вызове вручную (проверял на версиях 5.131, 5.140) метод работает и без указания полей, отмеченных в схеме обязательными. К тому же в [документации](https://vk.com/dev/market.edit) эти поля необязательны.

**Comment by aotd1** [comment]
Fixed in [v5.131.146](https://github.com/VKCOM/vk-api-schema/releases/tag/v5.131.146)
