### ISSUE TITLE
Не совпадают поля в схеме и документации

### ISSUE THREAD

**Issue by Olegt0rr** [VKCOM/vk-api-schema#206]
Версия API 5.131.
Метод `messages.delete`
В схеме поле называется `cmids`, в документации `conversation_message_ids`, на странице изменений нет никакой информации об этом.

Мы генерируем SDK на основании схемы, а потом пользователи не могут там найти поля из документации. Не круто :(

**Comment by aotd1** [comment]
Документацию изменили, спасибо. Схеме - верить)

**Comment by xeleoss** [comment]
Это я в ТП писал, поэтому обновили

**Comment by xeleoss** [comment]
Не, схеме еще верить нельзя, как минимум в методе photos.getMessagesUploadServer нету параметра peer_id.
