### ISSUE TITLE
Fix typo in `messages.getLongPollHistory` (`pts` parameter)

### ISSUE THREAD

**Issue by ablearthy** [VKCOM/vk-api-schema#210]
Here's [the line](https://github.com/VKCOM/vk-api-schema/blob/master/methods.json#L12575)

>  "description": "**Lsat** value of 'pts' parameter returned from the Long Poll..."

**Comment by aotd1** [comment]
Fixed in [v5.131.146](https://github.com/VKCOM/vk-api-schema/releases/tag/v5.131.146)
