### ISSUE TITLE
Поле объекта audio_save_response не соотвествует описанию

### ISSUE THREAD

**Issue by monterreyxdd** [VKCOM/vk-api-schema#22]
Поле **response** объекта **audio_save_response** в файле **responses.json** имеет тип array, что не соответвует описанию, а также не совпадает с фактическим результатом. Результат не является массивом.
[Ссылка на документацию](https://vk.com/dev/upload_files_2?f=8.%20%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0%20%D0%B0%D1%83%D0%B4%D0%B8%D0%BE%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B5%D0%B9)

**Comment by tsivarev** [comment]
Audio API is deprecated(
