### ISSUE TITLE
ВЫ ИЗДЕВАЕТЕСЬ???

### ISSUE THREAD

**Issue by FeeeeK** [VKCOM/vk-api-schema#231]
Я конечно понимаю, что вам абсолютно нет дела до сторонних разработчиков, но в этот раз вы превзошли все мои ожидания.
 Вы поменяли всю структуру схемы, хорошо, ладно, хоть это и внезапно сломало весь кодген, но ничего, вы ведь исправили ошибки? Да? Нет. 
Это реально какой-то сюр, **8 МЕСЯЦЕВ ПЕРЕКЛАДЫВАТЬ ЖСОНЫ И НЕ ИСПРАИВТЬ НИ ОДНОЙ ОШИБКИ**??? У вас 49 открытых ишью и вы забиваете на это? Мне надоело постоянно исправлять каждую фигню, которую вы выкатываете на прод и не добавляете в схему. Ради этого приходится использовать костыли и манкипатчинг. Почему приходится прибегать к таким извращениям из-за ваших ошибок?

Если вам так лень следить за ними, то вот, пожалуйста, исправленный код по тому, что на самом деле отправляет сервер:
https://github.com/vkbottle/types/blob/master/vkbottle_types/objects.py
https://github.com/vkbottle/types/tree/master/vkbottle_types/methods
https://github.com/vkbottle/types/tree/master/vkbottle_types/responses
Надеюсь, что вы сможете разобраться в коде на python.

**Comment by vypivshiy** [comment]
С понедельника программы ВКонтакте не будет!😨😨😨 Её полностью удаляют!(( Нам сидеть ВКонтакте осталось совсем чуть-чуть! Так, вот, чтобы все твои переписки, и картинки, и фотки не разошлись по всему инету кинь себе на стенку вот это! ВКонтакте теперь является публичной компанией! Именно, поэтому всем пользователям данной социальной сети рекомендуется разместить на своих страницах подобное «уведомление приватности», в противном случае (если уведомление не опубликовано на странице хотя бы однажды), вы автоматически разрешаете любое использование данных с вашей страницы, ваших фотографий и информации, опубликованной в сообщениях на стене вашей страницы!Каждый, кто читает этот текст, может скопировать его на свою стену в ВКонтакте! После этого вы будете находиться под защитой законов об авторском праве! Этот коммюнике оповещает ВКонтакте о том, что разглашение, копирование, распространение моей личной информации или любые другие противоправные действия по отношению к моему профилю в социальной сети строго запрещены
![image](https://user-images.githubusercontent.com/59173419/193770729-d0b7f702-f90f-4d5b-8b03-3987dd29c026.png)

**Comment by vypivshiy** [comment]
Схему сломали =( Все 8 лет её использовал такого не было никогда...
Это, Вк, Мейлру всё наделали!!!  

![image](https://user-images.githubusercontent.com/59173419/193771291-4f629bfa-df18-4ae4-a11f-3762274cd035.png)

**Comment by VodoGamer** [comment]
С понедельника программы вконтакте не будет ее полностью удаляют!
Нам сидеть вконтакте осталось совсем чуть-чуть!
Так вот чтобы все твои переписки и картинки фотки не разошлись по всему нету кинь себе на стенку вот это-В ответ на новую политику "ВКонтакте" я настоящим объявляю,

что все мои персональные данные, фотографии, рисунки, переписка и так далее являются объектами моего авторского права (согласно Бернской Конвенции) . Для коммерческого использования всех вышеупомянутых объектов авторского права в каждом конкретном случае необходимо мое письменное разрешение.

"ВКонтакте" теперь является публичной компанией. Именно поэтому всем пользователям данной социальной сети рекомендуется разместить на своих страницах подобное «уведомление приватности» , в противном случае (если уведомление не опубликовано на странице хотя бы однажды) , вы автоматически разрешаете любое использование данных с вашей страницы, ваших фотографий и информации, опубликованной в сообщениях на стене вашей страницы.

Каждый, кто читает этот текст, может скопировать его на свою стену в "ВКонтакте". После этого вы будете находиться под защитой законов об авторском праве. Этот коммюнике оповещает "ВКонтакте" о том, что разглашение, копирование, распространение моей личной информации или любые другие противоправные действия по отношению к моему профилю в социальной сети строго запрещены.

**Comment by qxtony** [comment]
С понедельника программы вконтакте не будет ее полностью удаляют!
Нам сидеть вконтакте осталось совсем чуть-чуть!
Так вот чтобы все твои переписки и картинки фотки не разошлись по всему нету кинь себе на стенку вот это-В ответ на новую политику "ВКонтакте" я настоящим объявляю,

что все мои персональные данные, фотографии, рисунки, переписка и так далее являются объектами моего авторского права (согласно Бернской Конвенции) . Для коммерческого использования всех вышеупомянутых объектов авторского права в каждом конкретном случае необходимо мое письменное разрешение.

"ВКонтакте" теперь является публичной компанией. Именно поэтому всем пользователям данной социальной сети рекомендуется разместить на своих страницах подобное «уведомление приватности» , в противном случае (если уведомление не опубликовано на странице хотя бы однажды) , вы автоматически разрешаете любое использование данных с вашей страницы, ваших фотографий и информации, опубликованной в сообщениях на стене вашей страницы.

Каждый, кто читает этот текст, может скопировать его на свою стену в "ВКонтакте". После этого вы будете находиться под защитой законов об авторском праве. Этот коммюнике оповещает "ВКонтакте" о том, что разглашение, копирование, распространение моей личной информации или любые другие противоправные действия по отношению к моему профилю в социальной сети строго запрещены.

**Comment by aotd1** [comment]
Сожалею что наши изменения всё сломали. Выкладка публичной JSON-схемы нетривиальный процесс требующий согласований. Именно поэтому бэкпортинг исправлений ошибок такой неповоротливый и долгий.
Разделение схемы по секциям - вынужденная мера направленная как раз на восстановление релизного цикла сломанного в марте.

Данный релиз исключительно технический, не содержит фундаментальных правок. 
Которые не преминут появиться в скорости.

**Comment by kirillsaint** [comment]
С понедельника программы вконтакте не будет ее полностью удаляют!
Нам сидеть вконтакте осталось совсем чуть-чуть!
Так вот чтобы все твои переписки и картинки фотки не разошлись по всему нету кинь себе на стенку вот это-В ответ на новую политику "ВКонтакте" я настоящим объявляю,

что все мои персональные данные, фотографии, рисунки, переписка и так далее являются объектами моего авторского права (согласно Бернской Конвенции) . Для коммерческого использования всех вышеупомянутых объектов авторского права в каждом конкретном случае необходимо мое письменное разрешение.

"ВКонтакте" теперь является публичной компанией. Именно поэтому всем пользователям данной социальной сети рекомендуется разместить на своих страницах подобное «уведомление приватности» , в противном случае (если уведомление не опубликовано на странице хотя бы однажды) , вы автоматически разрешаете любое использование данных с вашей страницы, ваших фотографий и информации, опубликованной в сообщениях на стене вашей страницы.

Каждый, кто читает этот текст, может скопировать его на свою стену в "ВКонтакте". После этого вы будете находиться под защитой законов об авторском праве. Этот коммюнике оповещает "ВКонтакте" о том, что разглашение, копирование, распространение моей личной информации или любые другие противоправные действия по отношению к моему профилю в социальной сети строго запрещены.

**Comment by gepron1x** [comment]
С понедельника программы вконтакте не будет ее полностью удаляют!
Нам сидеть вконтакте осталось совсем чуть-чуть!
Так вот чтобы все твои переписки и картинки фотки не разошлись по всему нету кинь себе на стенку вот это-В ответ на новую политику "ВКонтакте" я настоящим объявляю,

что все мои персональные данные, фотографии, рисунки, переписка и так далее являются объектами моего авторского права (согласно Бернской Конвенции) . Для коммерческого использования всех вышеупомянутых объектов авторского права в каждом конкретном случае необходимо мое письменное разрешение.

"ВКонтакте" теперь является публичной компанией. Именно поэтому всем пользователям данной социальной сети рекомендуется разместить на своих страницах подобное «уведомление приватности» , в противном случае (если уведомление не опубликовано на странице хотя бы однажды) , вы автоматически разрешаете любое использование данных с вашей страницы, ваших фотографий и информации, опубликованной в сообщениях на стене вашей страницы.

Каждый, кто читает этот текст, может скопировать его на свою стену в "ВКонтакте". После этого вы будете находиться под защитой законов об авторском праве. Этот коммюнике оповещает "ВКонтакте" о том, что разглашение, копирование, распространение моей личной информации или любые другие противоправные действия по отношению к моему профилю в социальной сети строго запрещены.

**Comment by iamkisly** [comment]
![АСТАНОВИТЕСЬ](https://topwar.ru/uploads/posts/2022-01/251710614-uiaaagl1uea-1920.jpg)
