### ISSUE TITLE
Проблема с именем "2fa"

### ISSUE THREAD

**Issue by InRedikaWB** [VKCOM/vk-api-schema#48]
У типа "account_info" есть свойство "2fa_required", которые является не очень подходящим. Особенно, появляются проблемы при написании SDK так, как большинство языков не поддерживают названия переменных, которые начинаются с цифры

**Comment by Mobyman** [comment]
К сожалению, нет возможности поменять формат объекта. Одно из возможных решений - использовать префикс для свойств с названием-зарезервированным словом и для полей, начинающихся с цифры.
