### ISSUE TITLE
Дублирование ключей в методе wall.editAdsStealth

### ISSUE THREAD

**Issue by InRedikaWB** [VKCOM/vk-api-schema#50]
В методе `wall.editAdsStealth` дважды указан ключ `post_id`:
https://github.com/VKCOM/vk-api-schema/blob/master/methods.json#L5473

https://github.com/VKCOM/vk-api-schema/blob/master/methods.json#L5517

**Comment by Mobyman** [comment]
Спасибо, исправили.
