### ISSUE TITLE
Отсутствует тип "messages_message_action_photo"

### ISSUE THREAD

**Issue by InRedikaWB** [VKCOM/vk-api-schema#52]
Одним из полей "messages_message_action" указан тип "messages_message_action_photo", которого нет в objects.json
https://github.com/VKCOM/vk-api-schema/blob/master/objects.json#L5116

**Comment by SevereCloud** [comment]
Скорее всего это messages_chat_settings_photo

**Comment by InRedikaWB** [comment]
Это не отменяет наличия ошибки в схеме

**Comment by Mobyman** [comment]
Исправили, https://github.com/VKCOM/vk-api-schema/blob/master/objects.json#L5317
