### ISSUE TITLE
objects.json/apps_app отсутствует свойство friends

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#56]
https://github.com/VKCOM/vk-api-schema/blob/12c49e6d804bf2f3b6d16478ac2173d89dc515af/objects.json#L1495-L1597

>friends array - список идентификаторов друзей текущего пользователя, которые установили приложение (если был передан параметр return_friends = 1.)

https://vk.com/dev/objects/app

**Comment by Mobyman** [comment]
Спасибо, исправили!
