### ISSUE TITLE
Отсутствует описание объекта groups_address_timetable_day

### ISSUE THREAD

**Issue by khrabrovart** [VKCOM/vk-api-schema#58]
В объекте **groups_address_timetable** в файле **objects.json** ссылка указывает на объект **groups_address_timetable_day** из файла **objects.json**, однако такого объекта не существует.

Судя по ответам от API, объект имеет вид:
`{ "open_time": 1080, "close_time": 1380, "break_open_time": 0, "break_close_time": 0 }`

Из [официальной документации](https://vk.com/dev/objects/address):

> open_time, close_time — начало и конец рабочего дня. break_open_time, break_close_time - время перерыва.

**Comment by khrabrovart** [comment]
Судя по ответам от API, объект имеет вид:
` {
"open_time": 1080,
"close_time": 1380,
"break_open_time": 0,
"break_close_time": 0
}`

**Comment by Mobyman** [comment]
Спасибо, описание добавлено.
