### ISSUE TITLE
Отсутствует описание объекта messages_conversation_peer_type

### ISSUE THREAD

**Issue by khrabrovart** [VKCOM/vk-api-schema#60]
В объекте **messages_conversation_peer** в файле **objects.json** ссылка указывает на объект **messages_conversation_peer_type** из файла **objects.json**, однако такого объекта не существует.

Если верить [официальной документации](https://vk.com/dev/objects/conversation), то:
> type (string) — тип. Возможные значения: user, chat, group, email

**Comment by khrabrovart** [comment]
Если верить [официальной документации](https://vk.com/dev/objects/conversation), то:

> type (string) — тип. Возможные значения: user, chat, group, email

**Comment by Mobyman** [comment]
Спасибо, исправили!
