### ISSUE TITLE
Отсутствует описание объекта groups_address_work_info_status

### ISSUE THREAD

**Issue by khrabrovart** [VKCOM/vk-api-schema#61]
Отсутствует описание объекта **groups_address_work_info_status** в файле **objects.json** при наличии ссылок на этот объект.

В [официальной документации](https://vk.com/dev/objects/address) имеем:

> тип расписания. Возможные значения:
no_information — нет информации о расписании;
temporarily_closed — временно закрыто;
always_opened — открыто круглосуточно;
forever_closed — закрыто навсегда;
timetable — открыто в указанные часы работы. Для этого типа расписания необходимо передать параметр timetable;

**Comment by Mobyman** [comment]
Спасибо, исправлено!
