### ISSUE TITLE
storage.get с параметром keys возвращает массив

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-api-schema#66]
https://vk.com/dev/storage.get

Пример ответа при keys=test
```json
{"response":[{"key":"test","value":""}]}
```

https://github.com/VKCOM/vk-api-schema/blob/a47e6028a031b886fe35420643c84b573f8fca81/responses.json#L5103-L5110

Возможное решение - добавить `storage_get_keys_response`

P.S. Надо учитывать, что в некоторых языках названия структур в верблюжем стиле - названия `storage_getKeys_response` и  `storage_get_keys_response` совпадут

**Comment by Mobyman** [comment]
Спасибо, исправили!
