### ISSUE TITLE
`name_case` is an enum field, so it should provide enum values in responses.json

### ISSUE THREAD

**Issue by alsemyonov** [VKCOM/vk-api-schema#7]
There is a list of possible values for `name_case` parameter provided in the description of the parameter.

In some methods (e. g. `friends.getAvailableForCall`, see https://github.com/VKCOM/vk-api-schema/blob/master/methods.json#L2339) it even provides default values, according to an “imaginary enum”. 
But default value `0` is invalid for provided type `string`, so schema is invalid too.

Please, provide enums for `name_case` and other enum fields.

**Comment by alsemyonov** [comment]
Fix provided in #8.

**Comment by tsivarev** [comment]
@alsemyonov Спасибо за помощь! Действительно не хватало.
